Resources:
  DDDCloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DDDCloudWatchLogsPolicy
      Roles:
        - !Ref lambdaRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'